B3 t10. Custom views
Golgoroth22/rebrain-android pull request #11
Opened 2019-04-12 17:06 UTC by Golgoroth22

2019-04-13 16:45 UTC, r3tam requested changes
Все почти круто!

2019-04-13 16:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
Форматирование, лучше использовать рекомендации к стилю кода с оф. сайта.

2019-04-13 16:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomButtonView.kt
> +class CustomButtonView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
форматирование

2019-04-13 16:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +        val attributes = context.obtainStyledAttributes(attrs, R.styleable.CustomBottomBarView)
пока это видимо лишние строки)

2019-04-15 07:02 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(
https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

2019-04-15 07:02 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(
Лишний перевод строки здесь

2019-04-15 07:02 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(
Еще есть предложение доработки боттом бара: сейчас вы ставите слушатели событий конкретным кнопка по id. Можно завести enum с типами табов, и обрабатывать все одним слушателем внутри BottomBarView. 
Это будет проще и понятнее масштабировать.

2019-04-15 07:02 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private fun makeMainButtonGrey() {
все вот это должно быть внутри кастомной вью. Это не зона ответственности экрана

2019-04-15 07:02 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private fun makeMainButtonGrey() {
Например внутри боттом бара, а лучше самой кнопки с возможностью настройки

2019-04-18 07:12 UTC, r3tam requested changes

2019-04-18 07:12 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
разнгесите аргументы конструктора а отдельные строки
```
constructor(
    arg1,
    arg2
) : ExtendedClass() {


}
```

2019-04-18 07:12 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +    private fun buttonClick(view: View?) {
По поводу организации класа и вообще работы с кликом: удобно сделать enum, который описывает кнопки(действия по ним - это чаще всего экраны, которые будут открываться). А дальше использовать нечто такое:
```
private val tabButtonsMap by lazy {
        hashMapOf<MainTabType, BottomBarItemView>(
                MainTabType.TYP1 to bottom_bar_wallet_btn,
                MainTabType.TYPE2 to bottom_bar_news_btn,
        )
    }
```

При клике проходится по этой мапе и просто менять одно свойство через цикл.
```
fun updateSelection(selectedTabType: MainTabType = MainTabType.PORTFOLIO) {
        checkSelectedTab(selectedTabType)
        uncheckOtherTabs(selectedTabType)
    }

    private fun checkSelectedTab(selectedTabType: MainTabType) {
        tabButtonsMap[selectedTabType]?.setChecked(true)
    }

    private fun uncheckOtherTabs(selectedTabType: MainTabType) {
        tabButtonsMap.keys
                .filter { it != selectedTabType }
                .forEach {
                    tabButtonsMap[it]?.setChecked(false)
                }
    }
```

Это поможет избежать дублирования кода

2019-04-18 07:12 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +                    R.id.custom_bottom_bar_main_button -> main_activity_view_pager.currentItem =
Если будет enum  то здесь своетую передавать именно его, а не вью

2019-04-18 07:12 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +                        main_activity_view_pager.currentItem + 1
лучше сделать некоторую абстракцию над +/- 1, так как сейчас из этого куска кода не очень понятно что происходит.

2019-04-19 16:17 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(
Сделано

2019-04-19 16:17 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(context: Context, attrs: AttributeSet? = null) :
Сделано

2019-04-19 16:17 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +class CustomBottomBarView @JvmOverloads constructor(
Сделано

2019-04-19 16:18 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/custom_view/CustomBottomBarView.kt
> +    private fun buttonClick(view: View?) {
Сделано

2019-04-19 16:18 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +                    R.id.custom_bottom_bar_main_button -> main_activity_view_pager.currentItem =
Сделано

2019-04-19 16:18 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +                        main_activity_view_pager.currentItem + 1
Сделано

2019-04-20 14:16 UTC, merged