B3 t11. Change viewPager to FrameLayout
Golgoroth22/rebrain-android pull request #12
Opened 2019-04-21 16:25 UTC by Golgoroth22

2019-04-22 01:22 UTC, r3tam requested changes

2019-04-22 01:22 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        transaction.commit()
Попробуйте реализовать с помощью механизма detach/attach. Это пригодится в будущем.

2019-04-28 20:59 UTC, r3tam requested changes

2019-04-28 20:59 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        val transaction = supportFragmentManager.beginTransaction()
Думаю эту логику стоит постараться перенести в метод attachNewFragment. Например, проверит есть ли такой фрагмент в менеджере, и если нет: add, иначе: attach.

2019-04-29 16:54 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        val transaction = supportFragmentManager.beginTransaction()
Сделано!

2019-04-30 08:15 UTC, r3tam approved these changes
Сливайте

2019-04-30 15:34 UTC, merged