Work on task b4-t03. RecyclerView
Golgoroth22/rebrain-android pull request #15
Opened 2019-05-28 16:59 UTC by Golgoroth22

2019-05-29 06:08 UTC, r3tam requested changes

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    private lateinit var viewManager: RecyclerView.LayoutManager
Лучше layoutManager, или lm

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    private lateinit var viewAdapter: MainTabElementAdapter
Обычно называют просто adapter или добавляют перед семантику элементов внутри: shopsAdapter, productsAdapter...

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +        recyclerView = rootView.findViewById<RecyclerView>(R.id.fragment_main_tab_recycler).apply {
В котлин есть замечательная вещь: kotlinx.synthetic - она позволяет не вызывать findViewById, а просто указывать id вью в коде.

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +        recyclerView = rootView.findViewById<RecyclerView>(R.id.fragment_main_tab_recycler).apply {
Собственно из-за них отпадет надобность в свойстве recyclerView.

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +class MainTabElementAdapter(
Док

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    private val inflater: LayoutInflater = LayoutInflater.from(context)
Не стоит хранить ссылку на инфлейтер. Лишний объект в памяти не нужен.

2019-05-29 06:08 UTC, r3tam commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    context: Context?
И контекст здесь тоже не нужен, его можно вытянуть из parent в onCreateViewHolder

2019-05-29 06:08 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    inner class MainTabElementViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Перенесите вниз класса,чтобы не мешал глазам.

2019-05-29 06:08 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    inner class MainTabElementViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
Да, и лучше раздувать необходимую вью прям в этом классе(сюда можно передать парента)

2019-05-29 06:08 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    fun setProductList(list: List<Any?>) {
Почему Any?

2019-05-29 06:08 UTC, artem-zaitsev commented on app/src/main/res/layout/card_main_element.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Забыл добавить дизайн в задание: https://zpl.io/aBBEApk

2019-06-01 16:03 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    private lateinit var viewManager: RecyclerView.LayoutManager
Fixed

2019-06-01 16:03 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    private lateinit var viewAdapter: MainTabElementAdapter
Fixed

2019-06-01 16:07 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +        recyclerView = rootView.findViewById<RecyclerView>(R.id.fragment_main_tab_recycler).apply {
Fixed

2019-06-01 16:10 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +class MainTabElementAdapter(
Fixed

2019-06-01 16:26 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    private val inflater: LayoutInflater = LayoutInflater.from(context)
Fixed

2019-06-01 16:26 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    context: Context?
Fixed

2019-06-01 16:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    fun setProductList(list: List<Any?>) {
Fixed

2019-06-03 05:01 UTC, r3tam approved these changes
Все ок

2019-06-03 05:43 UTC, merged