Work on task b4-t05. Add Glide
Golgoroth22/rebrain-android pull request #16
Opened 2019-06-03 06:46 UTC by Golgoroth22

2019-06-04 19:29 UTC, r3tam requested changes

2019-06-04 19:29 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
>          fun bind(product: Product) {
Сделайте отступ перед методом

2019-06-04 19:29 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/domain/Product.kt
> + * @param imageUrl Is a image of our object.
Обычно is не пишут в доках. Просто параметр и описание к нему

2019-06-04 19:29 UTC, artem-zaitsev commented on app/src/main/res/layout/card_main_element.xml
> +            android:padding="12dp"
откуда взялся этот паддинг?

2019-06-05 10:01 UTC, Golgoroth22 commented on app/src/main/res/layout/card_main_element.xml
> +            android:padding="12dp"
Fixed

2019-06-05 10:02 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
>          fun bind(product: Product) {
Fixed

2019-06-05 10:04 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/domain/Product.kt
> + * @param imageUrl Is a image of our object.
Fixed

2019-06-06 20:15 UTC, r3tam approved these changes
Сливайте

2019-06-11 04:36 UTC, merged