Work on task b4-t06. Переключение вида. Сетка
Golgoroth22/rebrain-android pull request #18
Opened 2019-06-12 17:38 UTC by Golgoroth22

2019-06-14 04:30 UTC, r3tam requested changes

2019-06-14 04:30 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        val displayMode = mainTabFragment.setRecyclerViewDisplay()
Почему-то геттер начинается с set...

2019-06-14 04:30 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        val displayMode = mainTabFragment.setRecyclerViewDisplay()
Разделите его на два метода, будет лучше читатся

2019-06-14 04:30 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    fun setRecyclerViewDisplay(): Boolean {
Поделите на два метода, один установка, другой возвращает текущее значение

2019-06-14 04:30 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    var displayMode = false
Лучше enum

2019-06-18 14:07 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        val displayMode = mainTabFragment.setRecyclerViewDisplay()
Исправил

2019-06-18 14:07 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    fun setRecyclerViewDisplay(): Boolean {
Исправил

2019-06-18 14:07 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    var displayMode = false
Исправил

2019-06-20 05:34 UTC, r3tam requested changes

2019-06-20 05:34 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private fun updateViews(item: MenuItem?) {
Лучше конкретно updateMenuItem

2019-06-20 05:34 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    fun setRecyclerViewDisplayMode() {
Сетттеры обычно что-то принимают. В вашем случае думаю лучше посмотреть в сторону invalidate/update

2019-06-22 09:48 UTC, r3tam requested changes

2019-06-22 09:48 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    fun updateRecyclerViewDisplayMode() {
М, возможно лучше toggle. Так как извне вроде ничего не изменяете. А просто переключаете режим

2019-06-22 09:48 UTC, artem-zaitsev commented on app/src/main/res/layout/card_main_grid_element.xml
> +            android:text="руб."
Не хардкодьте текст, пользуйтесь strings.xml

2019-06-22 09:48 UTC, artem-zaitsev commented on app/src/main/res/layout/card_main_grid_element.xml
> +            android:text="Название блюда"
Хардкод текста, используйте strings.xml

2019-06-22 14:53 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +    fun updateRecyclerViewDisplayMode() {
Исправил

2019-06-22 14:53 UTC, Golgoroth22 commented on app/src/main/res/layout/card_main_grid_element.xml
> +            android:text="руб."
Исправил

2019-06-22 14:53 UTC, Golgoroth22 commented on app/src/main/res/layout/card_main_grid_element.xml
> +            android:text="Название блюда"
Исправил

2019-06-23 10:28 UTC, r3tam approved these changes
Сливайте

2019-06-23 14:42 UTC, merged