Work on task b4-t07. Добавление карусели в общий список
Golgoroth22/rebrain-android pull request #19
Opened 2019-06-24 15:49 UTC by Golgoroth22

2019-06-27 04:40 UTC, r3tam requested changes
Отписался во фрешдеск.После правок ещё посмотрю

2019-07-05 14:23 UTC, r3tam requested changes

2019-07-05 14:23 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +        const val CAROUSEL_ID = 0
Лучше сделать через enum

2019-07-09 16:09 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +        const val CAROUSEL_ID = 0
Поправил

2019-07-11 09:20 UTC, r3tam requested changes
мелкие исправления

2019-07-11 09:20 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +            mainTabAdapter.setProductList(Generator().getProducts() as List<Product>, pageAdapter)
зачем явно приводить?

2019-07-11 09:20 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    var productList = mutableListOf<Any>()
тогда это уже не productList

2019-07-11 09:20 UTC, artem-zaitsev commented on app/src/main/res/values/colors.xml
> +    <color name="colorLineOpacity30">#4D000000</color>
не совсем понятно для чего этот цвет из его названия. И Opacity лучше указывать просто цифрой, ьез Opacity

2019-07-15 15:52 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +            mainTabAdapter.setProductList(Generator().getProducts() as List<Product>, pageAdapter)
Поправил

2019-07-15 15:52 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    var productList = mutableListOf<Any>()
Поправил

2019-07-15 16:01 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +            mainTabAdapter.setProductList(Generator().getProducts() as List<Product>, pageAdapter)
Поправил

2019-07-15 16:10 UTC, Golgoroth22 commented on app/src/main/res/values/colors.xml
> +    <color name="colorLineOpacity30">#4D000000</color>
Поправил

2019-07-16 20:45 UTC, r3tam requested changes

2019-07-16 20:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +        return MainTabProductViewHolder(
Можно inflate запихнуть внутрь ViewHolder. Таким образом он будет полностью ответственен за отображение конкретного элемента.

2019-07-17 08:23 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +        return MainTabProductViewHolder(
> Можно inflate запихнуть внутрь ViewHolder. Таким образом он будет полностью ответственен за отображение конкретного элемента.

Что-то у меня нету идей как это сделать. Нам же сразу нужно в конструктор холдера закидывать itemView : View сразу

2019-07-20 13:49 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +        return MainTabProductViewHolder(
Поправил!

2019-07-22 05:39 UTC, r3tam approved these changes
Сливайте

2019-07-28 15:33 UTC, merged