B5 t01 Lifecycle owner
Golgoroth22/rebrain-android pull request #29
Opened 2019-09-24 06:55 UTC by Golgoroth22

2019-09-25 08:32 UTC, r3tam reviewed
И также на данном этапе можно убрать логи из базовой реализации активити

2019-09-25 08:32 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        logger.onStart()
и все эти вызовы уберем

2019-09-25 08:32 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +class MainActivity : BaseActivity(), LifecycleOwner {
Уберем реализацию LifecycleOwner - она не нужна. 
Я поправлю задание.

2019-09-25 08:32 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/utils/Logger.kt
> +        lifecycle.addObserver(this)
как раз за счет этого, нам нет необходимости вызывать логгер напрямую

2019-10-03 04:20 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        logger.onStart()
Поправил!

2019-10-03 04:20 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +class MainActivity : BaseActivity(), LifecycleOwner {
Поправил

2019-10-03 04:20 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/Logger.kt
> +        lifecycle.addObserver(this)
Поправил

2019-10-03 04:21 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/Logger.kt
> +        lifecycle.addObserver(this)
Понял!

2019-10-03 07:13 UTC, r3tam requested changes
Небольшая правка

2019-10-03 07:13 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private val logger = Logger(lifecycle, Logger.Owner.MAIN_ACTIVITY)
В BaseActivity/Fragment

2019-10-07 07:31 UTC, r3tam requested changes
Перенесите создание логгера в базовые классы.

2019-10-07 07:31 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +    private val logger = Logger(lifecycle, Logger.Owner.INTRO_ACTIVITY)
Это должно быть в базовом классе. Если необходимо передать Owner, то можно сделать абстрактный метод у базового класса для этих  целей(или абстрактное свойство).

2019-10-10 06:37 UTC, r3tam approved these changes

2019-10-14 05:45 UTC, merged