B5 t02 ViewModel
Golgoroth22/rebrain-android pull request #30
Opened 2019-10-14 05:54 UTC by Golgoroth22

2019-10-14 08:02 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +    var picturesList: List<Int> = listOf(
Это будет муталбельное свойство?

2019-10-15 04:08 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +    var picturesList: List<Int> = listOf(
Поправил

2019-10-15 06:37 UTC, r3tam approved these changes

2019-10-15 06:37 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +    fun getProducts(): List<Any> {
документируйте публичные методы, это очень хорошая практика

2019-10-15 06:38 UTC, r3tam requested changes

2019-10-15 06:38 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +    fun getProducts(): List<Any> {
особенно при работе в командах

2019-10-16 08:03 UTC, r3tam approved these changes

2019-10-17 02:43 UTC, merged