[UPD] Work on b5-t03. Выделение Model-слоя
Golgoroth22/rebrain-android pull request #31
Opened 2019-10-17 05:21 UTC by Golgoroth22

2019-10-17 06:26 UTC, r3tam requested changes

2019-10-17 06:26 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/repository/ProductsRepository.kt
> +        R.drawable.food_1,
Если по правильному, то на данном этапе этот список надо перенести в Generator. А здесь обращаться к генератору.
Еще один момент для правильности: передавать источник данных в конструктор репозитория.

2019-10-17 08:55 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/ProductsRepository.kt
> +        R.drawable.food_1,
Поправил

2019-10-18 08:41 UTC, r3tam approved these changes
сливайте

2019-10-21 04:53 UTC, merged