[UPD] Work on b5-t04. LiveData. Наблюдаемые свойства
Golgoroth22/rebrain-android pull request #32
Opened 2019-10-21 08:58 UTC by Golgoroth22

2019-10-23 08:27 UTC, r3tam requested changes

2019-10-23 08:27 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +            productListViewModel.products.postValue(Generator().getProducts() as List<Product>?)
У Вас здесь и ниже во ViewModel по факту запрос к источнику данных. То, что в этой строке - это нарушение архитектуры и крайне нехорошо. Вся логика должна быть вo ViewModel. View максимально пассивна.

2019-10-25 04:01 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainTabFragment.kt
> +            productListViewModel.products.postValue(Generator().getProducts() as List<Product>?)
Поправил

2019-10-26 11:24 UTC, r3tam approved these changes

2019-10-28 03:02 UTC, merged