[UPD] Work on b5-t05. Выделение хранилища для режима отображения. v.1
Golgoroth22/rebrain-android pull request #33
Opened 2019-10-28 09:41 UTC by Golgoroth22

2019-10-29 07:14 UTC, r3tam requested changes

2019-10-29 07:14 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
> +    var productMode: Int
в этом классе не должно быть специфики. Он просто умеет складывать что-то в шеред префс. А уже что и по каким ключам - это логика стореджей.

2019-10-29 07:14 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/repository/ProductsDisplayModeRepository.kt
> +class ProductsDisplayModeRepository(val displayMode: ProductModeStorage)
сделайте тут методы для обращения к свойству, а само свойство сделайте приватным. Сокрытие реализации так сказать.

2019-10-29 07:14 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
>      var introInfo: Boolean
так же нужен сторедж под intro

2019-10-30 06:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/ProductsDisplayModeRepository.kt
> +class ProductsDisplayModeRepository(val displayMode: ProductModeStorage)
Поправить

2019-10-30 06:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
> +    var productMode: Int
Поправил

2019-10-30 06:49 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
>      var introInfo: Boolean
Вроде поправил

2019-10-30 07:00 UTC, r3tam approved these changes

2019-11-05 03:01 UTC, merged