B5 t10
Golgoroth22/rebrain-android pull request #38
Opened 2019-12-03 06:57 UTC by Golgoroth22

2019-12-03 11:14 UTC, r3tam requested changes

2019-12-03 11:14 UTC, artem-zaitsev commented on app/src/main/AndroidManifest.xml
> +        xmlns:tools="http://schemas.android.com/tools"
Все в целом отлично по ПР.
Провел небольшое ревью приложения в целом:
- Цвет текста в шапке неверный
- размеры индикаторов больше чем в дизайне
- [Положение карусели сбрасывается при переключении табов и режимов отображения
- иконка режима отображения "прыгает" при переключении из-за неверно заданных размеров
- закругоение углов у карточек не такое как в дизайне
- риппл у индикаторов лучше убрать
- акции лучше растянуть без белого фона

2019-12-05 05:30 UTC, Golgoroth22 commented on app/src/main/AndroidManifest.xml
> +        xmlns:tools="http://schemas.android.com/tools"
1. -
2. -
3. -
4. -
5. -
6. -
7. Поправил

2019-12-06 09:18 UTC, r3tam requested changes
По поводу inject с ViewModel - можете заглянуть в вот эту статью: https://medium.com/@vit.onix/dagger2-viewmodel-81d4cd59f642

Вообще Dagger это крайне обширная тема (и обновляющаяся).

2019-12-06 09:18 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +                DaggerAppComponent.builder().appModule(AppModule(context)).build()
Просто сделайте Storage аргументом метода provideFactory.
А дальше у вас компонент должен "предоставлять" этот сторэдж. И будет "магия" даггера

2019-12-06 09:18 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductModeStorageModule.kt
>      fun provideStorage(context: Context): Storage<Int> {
Должен принимать PrefHelper варгументом

2019-12-06 09:18 UTC, artem-zaitsev commented on app/src/main/res/drawable/ic_dot_off.xml
> +                android:thickness="7.3dp"
лучше использовать <size/> внутри тега <shape/>

2019-12-09 09:21 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +                DaggerAppComponent.builder().appModule(AppModule(context)).build()
Поправил

2019-12-09 09:26 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductModeStorageModule.kt
>      fun provideStorage(context: Context): Storage<Int> {
Поправил

2019-12-12 16:39 UTC, r3tam requested changes
маленькая правка

2019-12-12 16:39 UTC, artem-zaitsev commented on app/src/main/res/drawable/ic_dot_off.xml
> +                android:thickness="7.3dp"
тут видимо не отобразилось правильно:
```
лучше использовать<size/> внутри тега <shape/>
```

2019-12-24 07:25 UTC, r3tam approved these changes

2019-12-27 08:32 UTC, merged