B5 t11 Dagger. Scope
Golgoroth22/rebrain-android pull request #39
Opened 2019-12-27 08:54 UTC by Golgoroth22

2019-12-29 09:31 UTC, r3tam requested changes

2019-12-29 09:31 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/IntroViewModelFactoryModule.kt
> +    @PerApplication
нужна на все время жизни приложения? Скорее тут должен быть PerScreen.

2019-12-29 09:31 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +    @PerApplication
PerScreeen.
Вью модели редко переиспользуются между экранами. Скоуп  пер скрин - для зависимостей, которые необходимы конкретному экрану.

2019-12-30 10:32 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/IntroViewModelFactoryModule.kt
> +    @PerApplication
Пправил

2019-12-30 10:32 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +    @PerApplication
Поправил

2020-01-09 07:31 UTC, r3tam requested changes

2020-01-09 07:31 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/RebrainApp.kt
> +        lateinit var DAGGER: ScreenComponent
зачем приложение знает про . компоненты для экранов?

2020-01-09 07:31 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/component/ScreenComponent.kt
> +interface ScreenComponent {
должны быть отдельные компоненты для каждого экрана - иначе это все превратится в мусорку, когда экранов станет 5, 10, 20 ...

2020-01-14 08:56 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/RebrainApp.kt
> +        lateinit var DAGGER: ScreenComponent
Поправил

2020-01-14 08:56 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/component/ScreenComponent.kt
> +interface ScreenComponent {
Поправил

2020-01-15 07:47 UTC, r3tam requested changes

2020-01-15 07:47 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/splash/SplashActivity.kt
> +        DaggerAppComponent.builder().appModule(AppModule(this)).build()
Cделайте Application синглтоном и держите в нем ссылку на appComponent. Получайте компонент через эту ссылку.

2020-01-17 06:53 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/splash/SplashActivity.kt
> +        DaggerAppComponent.builder().appModule(AppModule(this)).build()
Поправил

2020-01-20 07:19 UTC, r3tam approved these changes
сливайте

2020-01-20 07:22 UTC, merged