B3 t02 v1.0
Golgoroth22/rebrain-android pull request #4
Opened 2019-03-07 18:10 UTC by Golgoroth22

2019-03-08 06:10 UTC, r3tam requested changes

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/splash/SplashActivity.kt
> +            prefHelper.introInfo = true
стоит делать при запуске экрана, внутри IntroActivity.

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
> +class PreferencesHelper(context: Context) {
Добавьте документацию к классу - это является хорошим тоном, и при работе в команде помогает быстрее вчитаться в чужой код

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_intro.xml
> +<android.support.constraint.ConstraintLayout
не хватает автоформатирования

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_intro.xml
> +            android:id="@+id/imageView3"
старайтесь давать имена идентификаторов по семантике элемента

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_intro.xml
> +
лишняя строка

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_intro.xml
> +            android:layout_marginStart="52dp" app:layout_constraintEnd_toEndOf="parent" android:layout_marginEnd="49dp"
странное форматирование

2019-03-08 06:10 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_intro.xml
> +            android:textSize="22sp"
настройки текста лучше вынести в стили текста и задавать через textAppereance

2019-03-09 07:48 UTC, r3tam requested changes

2019-03-09 07:48 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +            if (!PreferencesHelper(context).introInfo) PreferencesHelper(context).introInfo = true
наверно стоит перенести еще ближе к показу экрана, например в onCreate, вдруг произойдет ошибка на этапе создания вью и приложение упадет. При разработке Вам тогда придется каждый раз вручную чистить храниоище приложения..

2019-03-09 16:37 UTC, saturov requested changes

2019-03-09 16:37 UTC, saturov commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +        if (!PreferencesHelper(this).introInfo) PreferencesHelper(this).introInfo = true
Рекомендую не пренебрегать фигурными скобками в условных выражениях, даже если они однострочные. Если же всё-таки хочется, то советую не разносить по разным строкам условие и действие, т.е. в данном случае сделать перевод строки после ".intro)".

2019-03-09 16:37 UTC, saturov commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +
Как правило, пустая строка в теле метода - признак того, что метод можно и нужно декомпозировать на несколько более мелких.

2019-03-09 16:37 UTC, saturov commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +class IntroActivity : AppCompatActivity() {
Класс незадокументирован - это плохо.

2019-03-09 16:37 UTC, saturov commented on app/src/main/java/com/falin/valentin/foodapp/utils/PreferencesHelper.kt
> +        set(value) = preferences.edit().putBoolean(INTRO_INFO, value).apply()
Опасная ловушка котлина. Вместо того, чтобы вернуть значение в геттере - вы проинициализировали проперти. Если вдруг значение флага в SharedPreferences изменится после инициализации, но перед тем, как вы считаете значение повторно - то вы получите некорректное значение проперти и досадный баг, отловить который будет очень непросто.

2019-03-10 16:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +class IntroActivity : AppCompatActivity() {
Поправил!

2019-03-10 16:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/intro/IntroActivity.kt
> +
Поправил!

2019-03-11 17:40 UTC, r3tam approved these changes

2019-03-12 14:21 UTC, merged