B5 t12 Экран Избранное.
Golgoroth22/rebrain-android pull request #40
Opened 2020-01-22 10:36 UTC by Golgoroth22

2020-02-03 08:03 UTC, r3tam requested changes

2020-02-03 08:03 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/FavoriteProductListViewModel.kt
> +class FavoriteProductListViewModel(productsRepository: FavoriteProductsRepository) :
Контент на этом экране должен зависеть от реального избранного. Пока здесь мокированные данные. Сделайте работающий механизм добавления в избранное в пределах сессии. Храните избранное в памяти.

2020-02-04 07:11 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/FavoriteProductListViewModel.kt
> +class FavoriteProductListViewModel(productsRepository: FavoriteProductsRepository) :
Поправил

2020-02-05 08:11 UTC, r3tam requested changes

2020-02-05 08:11 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +            transaction.detach(supportFragmentManager.findFragmentById(R.id.main_activity_frame_layout) as BaseFragment)
есть подозрение, что в этой строке пропущен id

2020-02-05 08:11 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +                RebrainApp.DAGGER.favoriteProductsStorage().removeProduct(product)
ммм, это не очень хороший вариант.
лучше из адаптера пробросить колббек и обрабатывать нажатие извне

2020-02-05 08:11 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    private val favorites: FavoriteProductsStorage = RebrainApp.DAGGER.favoriteProductsStorage()
выше писал. Лучше из колбека на экране работать со стореджем

2020-02-05 08:11 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    private val favorites: FavoriteProductsStorage = RebrainApp.DAGGER.favoriteProductsStorage()
Там он у вас спокойно заижектится

2020-02-06 07:14 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +            transaction.detach(supportFragmentManager.findFragmentById(R.id.main_activity_frame_layout) as BaseFragment)
Вроде работает

2020-02-06 07:14 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +                RebrainApp.DAGGER.favoriteProductsStorage().removeProduct(product)
Поправил

2020-02-06 07:14 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/MainTabElementAdapter.kt
> +    private val favorites: FavoriteProductsStorage = RebrainApp.DAGGER.favoriteProductsStorage()
Поправил

2020-02-07 10:53 UTC, r3tam requested changes

2020-02-07 10:53 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/interactor/AddProductCallback.kt
> +interface AddProductCallback {
зачем? В Котлин такие интерфейсы с легкостью заменяются на лямбды.

2020-02-07 10:53 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/interactor/RemoveProductCallback.kt
> +interface RemoveProductCallback {
Такой же вопрос что и выше

2020-02-08 16:16 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/interactor/AddProductCallback.kt
> +interface AddProductCallback {
Вроде поправил

2020-02-08 16:16 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/interactor/RemoveProductCallback.kt
> +interface RemoveProductCallback {
Вроде поправил

2020-02-11 06:07 UTC, r3tam requested changes

2020-02-11 06:07 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +    constructor(favoriteProducts: FavoriteProductsStorage) : this() {
почему не в главном конструкторе? У Вас есть ситуация, когда адаптер создается без коллбека?

2020-02-11 12:38 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +    constructor(favoriteProducts: FavoriteProductsStorage) : this() {
И правда! Поправил

2020-02-12 07:17 UTC, r3tam requested changes

2020-02-12 07:17 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +    init {
Я не это имел ввиду.

2020-02-12 07:17 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +class FavoriteTabElementAdapter(favoriteProducts: FavoriteProductsStorage) :
``
```suggestion
class FavoriteTabElementAdapter(onClickListener: (Product) -> Unit) :
```

2020-02-12 07:17 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +    init {
и на setOnClickListener ставить ставить обработчик предложенной мной выше

2020-02-12 13:41 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/adapter/FavoriteTabElementAdapter.kt
> +    init {
Поправил

2020-02-13 06:43 UTC, r3tam approved these changes

2020-02-13 06:47 UTC, merged