[UPD] Work on b6-t01. 1. OkHttp - главный по всем клиентам. v.1
Golgoroth22/rebrain-android pull request #41
Opened 2020-02-15 07:27 UTC by Golgoroth22

2020-02-17 07:45 UTC, r3tam requested changes

2020-02-17 07:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/OkHttpModule.kt
> +        return OkHttpClient().newBuilder().addNetworkInterceptor(object : Interceptor {
лучше интерцепторы в отдельные классы выделять. Их может быть много.

2020-02-17 07:45 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +            ProductsRepository(Generator()), ProductsDisplayModeRepository(storage), OkHttpClient()
Странно: здесь создается новый инстанс клиента, хотя в апп компоненте он уже есть. Зачем?

2020-02-19 07:15 UTC, r3tam requested changes

2020-02-19 07:15 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
>          val request = Request.Builder()
послать сам запрос правильнее всего в репозитории.

2020-02-19 07:15 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +        RebrainApp.DAGGER.context()
Что делает эта строка?

2020-02-19 11:35 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
>          val request = Request.Builder()
Поправил

2020-02-19 11:35 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/ProductListViewModel.kt
> +        RebrainApp.DAGGER.context()
И правда. Убрал xD

2020-02-19 11:35 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/ProductListViewModelFactoryModule.kt
> +            ProductsRepository(Generator()), ProductsDisplayModeRepository(storage), OkHttpClient()
Поправил

2020-02-19 11:35 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/OkHttpModule.kt
> +        return OkHttpClient().newBuilder().addNetworkInterceptor(object : Interceptor {
Поправил

2020-02-20 07:17 UTC, r3tam approved these changes

2020-02-23 16:13 UTC, merged