[UPD] Work on b6-t02. Retrofit - помощник для сервисного слоя. v.1
Golgoroth22/rebrain-android pull request #42
Opened 2020-02-23 16:14 UTC by Golgoroth22

2020-02-25 07:20 UTC, r3tam requested changes

2020-02-25 07:20 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/component/AppComponent.kt
> +    fun retrofit(): Retrofit
В компоненте декларируется то, что будет проброшено с помощью инжекта в поле.
Если необходимы зависимости между модулями одного скоупа, то нет необходимости прописывать в компоненте. Даггер поймет, что необходимо тому или иному модулю, по сигнатуре метода provides(а точнее по типам аргусентов и возвращаемому значению)

2020-02-25 07:20 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .baseUrl("http://api.android.srwx.net/api/v2/")
лучше через отделльный метод provide поставлять урл

2020-02-26 13:25 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/component/AppComponent.kt
> +    fun retrofit(): Retrofit
Разобрался! Поправил

2020-02-26 13:25 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .baseUrl("http://api.android.srwx.net/api/v2/")
Поправил

2020-02-27 07:27 UTC, r3tam requested changes

2020-02-27 07:27 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .baseUrl(provideUrl())
Не, не совсем так.

Методы @Provides работают примерно так(учитывая даггеровский кодген):
p1(a: A): B и p2(): A даггеер читает как из метода p2 запровайдить тип А в p1. При этом даггер видит только типы. И что самое главное нет необходимости ]вным образом вызывать provide, даггер это сделает сам "под капотом".

Замечание: из-за того что Даггер вилит только типы могут случаться коллизии как два метода провайдят тип В(особенно это касается простейших типов) - это разруливается с помощью Named.

2020-02-27 15:05 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .baseUrl(provideUrl())
Понял

2020-02-28 07:09 UTC, r3tam requested changes

2020-02-28 07:09 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +    fun provideRetrofit(okHttpClient: OkHttpClient, url: String): Retrofit {
Лучше сразу сделать с помощью `@Named`

2020-03-03 13:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +    fun provideRetrofit(okHttpClient: OkHttpClient, url: String): Retrofit {
Сделал

2020-03-04 07:56 UTC, r3tam approved these changes

2020-03-04 14:04 UTC, merged