[UPD] Work on b6-t03. Moshi. Готовим Json правильно.
Golgoroth22/rebrain-android pull request #43
Opened 2020-03-05 15:15 UTC by Golgoroth22

2020-03-06 06:33 UTC, r3tam requested changes

2020-03-06 06:33 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .addConverterFactory(MoshiConverterFactory.create(Moshi.Builder().build()))
Сделайте отдельный провайд для фабрики конвертеров.

2020-03-06 15:27 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/di/module/RetrofitModule.kt
> +            .addConverterFactory(MoshiConverterFactory.create(Moshi.Builder().build()))
Готово

2020-03-10 07:51 UTC, r3tam approved these changes

2020-03-11 15:26 UTC, merged