B6 t04
Golgoroth22/rebrain-android pull request #44
Opened 2020-03-13 09:08 UTC by Golgoroth22

2020-03-16 07:27 UTC, r3tam requested changes

2020-03-16 07:27 UTC, artem-zaitsev commented on app/build.gradle
> +    implementation "com.google.firebase:firebase-analytics:$firebase_analytics"
а зачем аналитика?

2020-03-16 07:27 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/service/AppFirebaseMessaging.kt
> +        createNotificationChannel()
В общем случае у разных нотификаций в приложении могут быть разные каналы. Поэтому лучше создавать его при получении нотификации из файербейз.
Также лучше вынести проверку сдк из =метода - будет нагляднее, а сам метод пометить анотацией RfequiresApi

2020-03-18 14:13 UTC, Golgoroth22 commented on app/build.gradle
> +    implementation "com.google.firebase:firebase-analytics:$firebase_analytics"
Убрал

2020-03-18 14:13 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/service/AppFirebaseMessaging.kt
> +        createNotificationChannel()
Вроде поправил

2020-03-19 06:03 UTC, midery approved these changes

2020-03-19 08:03 UTC, merged