B6-t05. Авторизация и Таб Профиль
Golgoroth22/rebrain-android pull request #45
Opened 2020-03-28 04:39 UTC by Golgoroth22

2020-03-29 15:46 UTC, midery requested changes

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/interactor/UserDataStorage.kt
> +    fun getEmail() = preferencesHelper.userEmail
Здесь нейминг методов не единообразный: метод для извлечения токена без get-префикса, а для email - с префиксом. 
Лучше всегда использовать get/set префиксы в методах, и не юзать их в свойствах.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/interactor/AuthorizationStorage.kt
> +    fun setUserAuthorizationStatus() {
С помощью этого storage мы не сможем установить юзеру разлогиненное состояние. 
По-моему, это некорректное поведение. Следует либо сделать 2 метода: setUsedAuthorized / setUserUnauthorized, либо просто создать свосйство isUserAuthorized, которое будет извлекать и сеттить поле из preferencesHelper.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/LoggingInterceptor.kt
> +        Timber.i("Sending request body\n${requestBodyTo(request)}")
https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor можно, кстати, использовать этот интерсептор. Он выводит всю нужную инфу, и очень прост в использовании.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/pojo/login/LoginRequest.kt
> +data class LoginRequest(
В таких классах лучше указывать имена полей аннотацией @SerializedName. Без этого, при обфускации сервер будет получать невалидные данные.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountTabRepository.kt
> +class AccountTabRepository(
Репозитории  - это объекты, которые инкапсулируют собой логику работы с данными, и не зависят от экрана приложения. Они должны зависеть от юзкейсов. А вот экраны уже в свою очередь будут зависеть от репозиториев.
Приведу пример: 
У тебя сейчас AccountTabRepository, но по факту он может использоваться везде, где нужно узнать, авторизован юзер, или нет. То есть, это скорее AuthorizationStatusRepository. И его вполне можно заинжектить в AuthorizationRepository, который расположен ниже.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        if (email.contains("@") &&
Для проверки email в андроиде есть регулярное выражение: Patterns.EMAIL. Можешь использовать его. А для пароля достаточно проверки на то, что он больше 4-ех символов. Остальное лучше не добавлять.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        }.also {
Лучше не увлекаться сахаром котлина, он может сделать код нечитаемым. Очень сложно разбираться в таком коде из also и it-переменных. Гораздо проще будет:
```
val textChangedListener = object : TextWatcher { ... } 
fragment_authorization_emailEditText.addTextChangedListener(textChangedListener)
fragment_authorization_passwordEditText.addTextChangedListener(textChangedListener).
```

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +                if (chars != null) {
Мне кажется, что кнопка должна становиться кликабельной, только когда оба поля заполнены, а не только одно.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            rootView.fragment_authorization_emailEditText.addTextChangedListener(it)
Здесь можно не обращаться к rootView, а юзать прямой доступ к переменным из синтетика:
`fragment_authorization_emailEditText.addTextChangedListener(it)`

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +class AuthorizationFragment : BaseFragment(), ServerResponseCallback {
Лучше по-возможности избегать такой записи: вью никогда не должен быть Callback'ом сетевых запросов. Эту роль должна выполнять ViewModel, а вью, в свою очередь, только отображает то, что скажет ей ViewModel. Сейчас же ответственность расплылась, и не очень ясно, что именно следует делать) Но вообще, модель с коллбеками сейчас уже почти не используется, так что попробую подсказать, как лучше организовать код (оставил комменты к репозиторию)

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AuthorizationRepository.kt
> +    private val callback: ServerResponseCallback
У этого репозитория может быть несколько методов (авторизация по логину/паролю, сброс пароля, итд), поэтому одного коллбека недостаточно. Плюс, onFailure может вызваться, когда фрагмент уже уничтожится, и это приведет к NullPointerException и крешам.
Подходов по построению запросов к серверу достаточно много (kotlin coroutines + try/catch, rxJava, flow). Для начала, я советую попробовать поработать с MutableLiveData, так как здесь все будет проще всего. 

1. Передаешь прямо в метод login у репозитория 2 коллбека: `onSuccess: (User) -> Unit` и `onFailure: (T) -> Unit`. 
2. Вызываешь их во ViewModel, и изменяешь MutableLiveData так, как тебе нужно. Можешь завести несколько LiveData для отображения загрузки / ошибки / успеха, либо сделать класс вроде 
```
data class LoginUi { 
  val data: User? = null,
  val isLoading = false,
  val error: Throwable = null 
}
```
Чтобы в нем хранить информацию о текущем состоянии ui, и уже данные оборачивать в MutableLiveData.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +    lateinit var userData: UserDataStorage
view не может напрямую взаимодействовать со storage (как и viewModel, кстати). 
view взаимодействует только с ViewModel, ViewModel только с repo, а repo, в свою очередь, со storage

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            if (isEmailAndPasswordValid(email, pass)) {
Проверка валидности имени и пароля - зависимость ViewModel, все проверки должны быть там. View только отправляет ей значения своих полей.

2020-03-29 15:46 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        object : TextWatcher {
Кстати, для упрощения написания TextWatcher'ов обычно на проектах пишем extension-функцию для EditText: 
```
fun EditText.setOnTextChanged(onTextChanged: (String) -> Unit) {
    this.addTextChangedListener(object : TextWatcher {
        override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) {}

        override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) {
            removeTextChangedListener(this)
            onTextChanged.invoke(s?.toString() ?: EMPTY_STRING)
            addTextChangedListener(this)
        }

        override fun afterTextChanged(s: Editable?) {}
    })
}
```
Обычно очень сильно упрощает чтение подобных кусков кода. Можешь и у себя его заюзать.

2020-04-13 04:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/interactor/UserDataStorage.kt
> +    fun getEmail() = preferencesHelper.userEmail
Понял! Поправил

2020-04-13 04:50 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/interactor/AuthorizationStorage.kt
> +    fun setUserAuthorizationStatus() {
Понял! Поправил

2020-04-13 05:01 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/LoggingInterceptor.kt
> +        Timber.i("Sending request body\n${requestBodyTo(request)}")
Понял! Буду иметь ввиду

2020-04-13 05:03 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/pojo/login/LoginRequest.kt
> +data class LoginRequest(
Понял! Поправил

2020-04-13 05:15 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountTabRepository.kt
> +class AccountTabRepository(
Понял1

2020-04-13 08:32 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        if (email.contains("@") &&
Понял! Поправил

2020-04-13 08:40 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        }.also {
Хорошо, понял!

2020-04-13 08:55 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            rootView.fragment_authorization_emailEditText.addTextChangedListener(it)
Хмм. Хорошо

2020-04-13 08:55 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +                if (chars != null) {
Логично!

2020-04-16 12:39 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +class AuthorizationFragment : BaseFragment(), ServerResponseCallback {
Понял!

2020-04-16 12:39 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AuthorizationRepository.kt
> +    private val callback: ServerResponseCallback
Переделал. Надеюсь правильно понял принцип :)

2020-04-17 14:19 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +    lateinit var userData: UserDataStorage
Понял!

2020-04-17 14:35 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            if (isEmailAndPasswordValid(email, pass)) {
Хорошо, буду знать!

2020-04-17 14:53 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        object : TextWatcher {
О, спасибо!

2020-04-20 11:07 UTC, midery requested changes

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AuthorizationFragmentViewModel.kt
> +    val loadingLiveData = MutableLiveData<Boolean>()
Эта liveData у тебя всегда эмитит false. Она точно валидно себя ведет?)

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AuthorizationFragmentViewModel.kt
> +    val messageResponseLiveData = MutableLiveData<String>()
Лучше скрывать MutableLiveData за геттерами, чтобы вьюха не могла их изменять. 
Например:

```
private val mMessageResponseLiveData = MutableLiveData<String>()
val messageReponseLiveData: LiveData<String>() = mMessageResponseLiveData
```
Это обеспечит более прозрачный интерфейс взаимодействия вьюхи и viewModel, и поможет в выстроении однонаправленного потока данных (unidirectional data flow). Очень полезная штука на больших проектах, потому что с помощью нее флоу работы с вьюхой всегда максимально прост и понятен)

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            setViewsDisabled()
лучше это отдать на откуп полю с состоянием загрузки: 
в реальных приложениях загрузка может начаться не только по нажатию на кнопку, но и, например, при скролле экрана, при оттягивании SwipeRefresh, автоматически при заходе на экран: и во всех этих случаях нужно отобразить одно и то же состояние загрузки.
Лучше инкапсулировать его в поле ViewModel с состояниями true/false, и реагировать на его изменение.
Так же, хорошей практикой является хранение всех данных, необходимых для показа запроса на Ui, в одной сущности:
`LoginUiResponse(data: User, isLoading: Boolean, error: Throwable)`

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            if (it) {
Лучше использовать именованные параметры, иначе здесь не очень понятно, что за it) 
Какой-нибудь isLoading, например

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +        rootView.fragment_account_userNameText.text = viewModel.getUserEmail()
мы ведь работаем с viewModel на основе liveData, просто вытаскивать у нее свойства не принято)

2020-04-20 11:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/domain/LoginUiResponse.kt
> +data class LoginUiResponse(
Немного некорректно возвращать этот респонс из репозитория. 
Репо не знает ничего про ui, по факту, он может использоваться даже без ui) 
И по-моему, httpMessage нигде не используется и передавать его нужно. Так что можно просто обойтись возвращением UserResponse.

2020-04-27 04:47 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AuthorizationFragmentViewModel.kt
> +    val loadingLiveData = MutableLiveData<Boolean>()
И правда xD

2020-04-27 04:58 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AuthorizationFragmentViewModel.kt
> +    val messageResponseLiveData = MutableLiveData<String>()
Понял!

2020-04-27 05:49 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            setViewsDisabled()
Хорошо

2020-04-27 05:53 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +            if (it) {
Понял!

2020-04-27 05:58 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/domain/LoginUiResponse.kt
> +data class LoginUiResponse(
Хмм, хорощо

2020-04-27 06:04 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +        rootView.fragment_account_userNameText.text = viewModel.getUserEmail()
Хорошо

2020-04-27 08:03 UTC, midery approved these changes

2020-04-27 08:16 UTC, merged