[UPD] Work on b6-t06. Редактирование профиля. v0.1
Golgoroth22/rebrain-android pull request #46
Opened 2020-05-01 09:15 UTC by Golgoroth22

2020-05-05 13:07 UTC, midery requested changes
Запустил проект, есть общие замечания по работоспособности предыдущих экранов:
1. При нажатии на кнопку "Профиля" на главной ты каждый раз добавялешь новый фрагмент, а так делать нельзя, это может привести к out of memory error. 
2. На экране логина при ошибке валидации поля никак не подсвечиваются, и пользователь не может понять, почему у него задизейблена кнопка и он ничего не может сделать. Плюс, дизейбл кнопки ничем не отличается от активного состояния, из-за чего есть ощущение, что запрос просто не проходит.
3. Экран логина не ресайзится при появлении клавиатуры, из-за чего на маленьких девайсах просто невозможно перейти с поля ввода емейл на поле ввода. Советую обернуть экран в ScrollView.
4. Экран логина сейчас находится в контексте главной, а должен быть перед ней, так как для получения товаров необходим accessToken. 
Это не слишком критично, можно оставить, т.к. в некоторых приложениях это частое пожелание.
Критичным является то, что на логине и профиле туллбар с таба "Главный", но его там однозначно быть не должно по дизайну.
Так же то, что логин по дизайну должен отображаться поверх боттом-бара с табами "Профиль, Главный, Избранное", сейчас он находится на этом баре, и даже поднимает его вместе с клавиатурой. Это некорректное поведение, и его нужно устранить. 
5. При логине пользователь должен сразу же перемещаться на таб профиля, сейчас нужно перезапустить приложение, чтобы таб сменился

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/domain/AccountUiResponse.kt
> + * This is a data class for work with [AccountFragment].
Лучше не привязывать ui-модельку к конкретному экрану, один и тот же ui-респонс может использоваться на разных экранах.

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +class AccountFragmentRepository(
По-моему, мы уже говорили про то, что лучше бы не вставлять в репозитории андроид-сущности. Репо не должен зависеть от платформы.

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +        bitmap: Bitmap,
parentDir - это ведь просто context.cacheDir, а contentResolver - это context.contentResolver. Не лучше ли будет просто запровайдить контекст в репозиторий, без этого прокидывания ui-сущностей в него?

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +    private lateinit var rootView: View
Зачем здесь rootView? Все kotlin android extensions спокойно работают с фрагментом напрямую, незачем добавлять эту прослойку здесь

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            startActivityForResult(Intent(MediaStore.ACTION_IMAGE_CAPTURE), 2020)
Интересно, зачем тут 2020?) Это обязательно нужно вынести в константу, причем желательно более уникальную)

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +        private const val CAMERA_REQUEST_CODE = 2020
Константа есть но почему-то она не используется во всех местах. Следи усерднее за состоянием кода перед подачей ПР, все должно быть уже подчищено и финализировано)

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
> +        @Part("description") description: RequestBody,
Зачем здесь этот параметр?

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
>      @PUT("user/avatar")
Немного неверный эндпоинт, должен быть слеш / в конце

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +                    if (scaledBitmap != null) {
По-моему, эта проверка избыточна, раз уж сверху ты явно скастил результат `as Bitmap`

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AccountFragmentViewModel.kt
> +        repository.tryToSendAvatar(
Название метода у репозитория довольно странное) Почему tryToSendAvatar, а метод у сервиса - putAvatar? Давай стараться сохранить единообразие. 
И там и там должно быть setAvatar

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +        val descriptionString = "hello, this is description speaking"
Подобного кода точно не должно быть в продакшне)

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +                response.body()?.let { onSuccess.invoke(it) }
Здесь игнорируется любой кейс, когда response.body() == null, и просто не обновляет вьюху. Это происходит при получении многих http-ошибок, например 403 или 405. Сейчас это и происходит. 

Да и вообще этот ретрофит-коллбек выглядит очень толстым. Предлагаю добавить небольшую обертку для него, чтобы работать проще и приятнее:

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +                response.body()?.let { onSuccess.invoke(it) }
```
package com.falin.valentin.foodapp.network.retrofit.service

import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response
import kotlin.IllegalStateException

class RetrofitCallback<T>(
    val onSuccess: (T) -> Unit,
    val onError: (Throwable) -> Unit
) : Callback<T> {

    override fun onFailure(call: Call<T>, t: Throwable) {
        onError(t)
    }

    override fun onResponse(call: Call<T>, response: Response<T>) {
        val body = response.body()
        if (response.isSuccessful && body != null) {
            onSuccess(body)
        } else {
            onError(IllegalStateException("Response must not be null: $response"))
        }
    }
}
```

Подобная штука будет менее вербозной, и к тому же будет обрабатывать все http-ошибки, и выдавать только не nullable-тело запроса

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
> +    ): Call<UserResponse>
Этот запрос возвращает не UserResponse, а Unit (в ответ приходит пустота, 200-ый код с сообщением об успехе). 

Это давно нужно было поправить в спецификации сваггера, поправили. 
Так же добавили описания в самом задании: https://my.rebrainme.com/mod/assign/view.php?id=190&forceview=1

Для того, чтобы все заработало, нужно в onSuccess еще выполнить UserService.getUser(), чтобы получить ссылку на аватар и актуальную инфу о пользователе.
Осторожно! метод getUser вернет пустой токен, поэтому будь к этому готов и не сохраняй токен из этого метода.

2020-05-05 13:07 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/domain/AccountUiResponse.kt
> +    val data: UserResponse? = null,
Сейчас у тебя из репозитория возвращается UserResponse, да и вообще приложение оперирует этими сущностями, userResponse. Это не совсем верно.
Чтобы сделать архитектуру расширяемой и строгой, обычно разработчики конвертируют сущности, приходящие с сервера (response-модель) в сущности приложения (domain-модель). Это нужно для того, чтобы приложение не слишком завязывалось на сервер, и могло само высчитывать/содержать нужные данные, и не хранить мусорный код с сервера. 
В нашем случае, советую конвертировать **UserResponse** в модельку **User**, в которой будут лежать те же поля, но без каких-либо аннотаций от moshi. 
Можно даже завести в общем случае интерфейс вроде BaseResponse<T>, у которого будет метод convert(): T, в котором ты сможешь конвертировать все модельки с сервера в доменные модели. 
И оперировать на выходе из репозитория уже доменными моделями. Конкретно в нашем случае - оперировать будем моделькой User.

2020-05-05 13:08 UTC, midery requested changes

2020-05-05 13:08 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +            .asRequestBody(contentResolver.getType(Uri.fromFile(file)).toMediaTypeOrNull())
Чтобы запрос не падал, можно просто убрать эту строку, и сделать просто file.asRequestBody()

2020-05-30 05:19 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/domain/AccountUiResponse.kt
> + * This is a data class for work with [AccountFragment].
Хорошо, понял!

2020-05-30 09:30 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +class AccountFragmentRepository(
Надеюсь я правильно понял. Поменял на интерфейсы

2020-05-30 09:55 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +    private lateinit var rootView: View
И правда. Понял

2020-05-31 14:27 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +        bitmap: Bitmap,
И правда! Понял

2020-05-31 14:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/AccountFragmentViewModel.kt
> +        repository.tryToSendAvatar(
Хорошо!

2020-05-31 14:39 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +        private const val CAMERA_REQUEST_CODE = 2020
Хорошо

2020-05-31 14:39 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            startActivityForResult(Intent(MediaStore.ACTION_IMAGE_CAPTURE), 2020)
Хорошо

2020-05-31 14:41 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
>      @PUT("user/avatar")
Поправил

2020-05-31 14:43 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +                    if (scaledBitmap != null) {
Точно

2020-05-31 14:49 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +            .asRequestBody(contentResolver.getType(Uri.fromFile(file)).toMediaTypeOrNull())
Поправил

2020-05-31 14:53 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
> +        @Part("description") description: RequestBody,
Убрал

2020-05-31 15:09 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +        val descriptionString = "hello, this is description speaking"
Будем исправляться)

2020-05-31 15:11 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/AccountFragmentRepository.kt
> +                response.body()?.let { onSuccess.invoke(it) }
Удобно!

2020-06-02 04:57 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/UserAvatarService.kt
> +    ): Call<UserResponse>
Понял!

2020-06-02 05:51 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/domain/AccountUiResponse.kt
> +    val data: UserResponse? = null,
Хорошо

2020-06-02 10:13 UTC, midery requested changes

2020-06-02 10:13 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountTabFragment.kt
> +            activity!!.main_activity_custom_bottom_bar.visibility = View.VISIBLE
Это не самая лучшая идея. Фрагмент не должен знать о том, какие у родительского экрана есть вьюхи, да и вообще о реализации родительского экрана.
Это базовые принципы реализации отношений parent-child. 
В текущей реализации самым простым решением было бы наличие у activity метода setBottombarVisibility(isVisible: Boolean), чтобы фрагмент рулил в зависимости от состояния авторизованности этим методом.

2020-06-02 10:13 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        this.fragment_authorization_authButton.isEnabled = false
Вполне можно убрать this и просто использовать эти вьюхи проперти так:
fragment_authorization_loadingProgress.visibility = View.VISIBLE

2020-06-02 14:46 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountTabFragment.kt
> +            activity!!.main_activity_custom_bottom_bar.visibility = View.VISIBLE
Хорошо

2020-06-02 14:46 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AuthorizationFragment.kt
> +        this.fragment_authorization_authButton.isEnabled = false
Поправил

2020-06-10 08:12 UTC, midery approved these changes

2020-06-11 03:02 UTC, merged