[UPD] Work on b6-t08. Экран с картой и пунктами самовывоза
Golgoroth22/rebrain-android pull request #48
Opened 2020-06-28 12:35 UTC by Golgoroth22

2020-06-28 19:16 UTC, midery requested changes

2020-06-28 19:16 UTC, midery commented on app/src/debug/res/values/google_maps_api.xml
> +    56:F6:D4:23:93:EA:50:54:C3:9A:A7:FE:E7:09:0C:44:D0:F9:33:F9
Эту информацию в реальных приложениях никогда не стоит пушить в репозиторий) 
Лучше убрать этот комментарий, либо добавить в файлик, который отмечен в gitignore

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/PickupsService.kt
>      fun getPickups(): Call<PickupsResponse>
Запрос сейчас возвращает в постмане довольно красноречивый ответ: 
```
{"detail":"no token provided"}
```
То есть, ему не хватает Auth токена пользователя. Попробуй достать его из хранилища и добавить. 
Вообще, сервер по какой-то причине немного изменил ответ, так что я внес в спецификацию обновления: https://gitlab.rebrainme.com/android-course/food-app-api/-/blob/master/food-app-openapi.yml
Можешь привести свой код к ним, и все заработает.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/MapActivityRepository.kt
> +     * This method can be called for take pickups.
Минимальное замечание, но все же: to take, for используется с существительным

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            context!!.launchActivity<MapActivity>()
можно использовать requireContext(), чтобы обойтись без !!-оператора.
Обычно его не юзаем в продакшне, это плохой тон.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +class MapActivity : BaseActivity(), OnMapReadyCallback, GoogleMap.OnMyLocationClickListener,
Точно ли активити должно наследовать столько сущностей? Тебе не кажется, что это перебор?) 

Мы пишем на kotlin, и такую запись: 
`map.setOnMyLocationButtonClickListener(this)`
Вполне можно заменить на 
`map.setOnMyLocationButtonClickListener(::onMyLocationButtonClick)`
И ничего в целом не изменится.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +    override fun onResumeFragments() {
Зачем делать это именно в onResumeFragments?

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +import com.falin.valentin.foodapp.utils.RationaleDialog.Companion.newInstance
Давай-ка лучше так не делать, я пару минут пытался понять, что тут происходит)

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +        if (activity_map_pickupRootLayout.visibility == View.VISIBLE) {
Молодец, что предусмотрел эту ситуацию, это прямо большой плюс для ux!
Кстати, можно использовать экстеншны view.isVisible, чтобы удобнее проставлять и считывать видимостью вьюх:
```
if (activity_map_pickupRootLayout.isVisible) { 
  activity_map_pickupRootLayout.isVisible = false 
} else ...
```

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            activity_map_pickupRootLayout.visibility = View.GONE
Не советую использовать snakeCase + camelCase в именовании одной переменной: это чужеродно выглядит, и очень плохо читается, как если бы человек сказал одно предложение на двух разных языках.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +                viewModel.pickups = response.data
Это нарушение архитектуры: view не может извлечь из viewModel значение, а потом заново его засеттить в нее. 
Если viewModel нужно извлечь значение из самой себя - она вполне может на это значение подписаться.
Но по факту нам это не нужно, потому что у mPickupsLiveData есть поле value, в котором всегда лежат нужные нам пункты выдачи.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            == PackageManager.PERMISSION_GRANTED
Тут код очень плохо читается. Мб сделать
``` 
val permissionResult = checkSelfPermission...
if (permissionResult == GRANTED) ...
```

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +         * @param finishActivity Whether the calling Activity should be finished if the dialog is
мб finishOnCancel? Иначе как-то очень странно получается)

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    fun getPickup(marker: Marker): PickupResponse? {
Здесь не должны фигурировать response-модели, это же ui-слой. Здесь должны быть только доменные модельки.

2020-06-28 19:16 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/domain/PickupsUiResponse.kt
> +data class PickupsUiResponse(
Почему этот класс лежит в пакете domain?) Это ведь uI-сущность, и должна быть в пакете с ui

2020-06-29 08:05 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/network/retrofit/service/PickupsService.kt
>      fun getPickups(): Call<PickupsResponse>
О как! Понял!

2020-06-29 09:45 UTC, Golgoroth22 commented on app/src/debug/res/values/google_maps_api.xml
> +    56:F6:D4:23:93:EA:50:54:C3:9A:A7:FE:E7:09:0C:44:D0:F9:33:F9
Понял!

2020-06-29 09:46 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/MapActivityRepository.kt
> +     * This method can be called for take pickups.
Точно!

2020-06-29 09:48 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            context!!.launchActivity<MapActivity>()
Буду знать, спасибо!

2020-06-29 10:08 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +class MapActivity : BaseActivity(), OnMapReadyCallback, GoogleMap.OnMyLocationClickListener,
Не знал. Почитаю подробнее про это

2020-06-29 10:13 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +    override fun onResumeFragments() {
Так было в сэмпле от гугла xD

2020-06-29 10:34 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +        if (activity_map_pickupRootLayout.visibility == View.VISIBLE) {
О, удобно!

2020-06-29 12:02 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            == PackageManager.PERMISSION_GRANTED
Окей!

2020-06-29 12:02 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +                viewModel.pickups = response.data
Понял

2020-06-29 12:02 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            activity_map_pickupRootLayout.visibility = View.GONE
Хорошо

2020-06-29 13:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    fun getPickup(marker: Marker): PickupResponse? {
Точно

2020-06-29 13:36 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/domain/PickupsUiResponse.kt
> +data class PickupsUiResponse(
Окей

2020-06-29 15:38 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +         * @param finishActivity Whether the calling Activity should be finished if the dialog is
Окей!

2020-07-01 15:12 UTC, midery requested changes

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/models/domain/LatLng.kt
> +data class LatLng(
Может быть назовем его location? Java и Kotlin учат нас быть вербозными и не сокращать имен. И предлагаю lat/lon так же развернуть.
Доменные модели должны быть именованы максимально просто и не абстрактно, как объекты реального мира.

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/models/domain/Pickup.kt
> +data class Pickup(
А вот здесь нейминг отличный, все ок)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/repository/MapActivityRepository.kt
> +    fun getPickups(
Раз уж ты попробовал себя в корутинах, не хочешь попробовать переписать эту функцию на них?) 
https://proandroiddev.com/suspend-what-youre-doing-retrofit-has-now-coroutines-support-c65bd09ba067 Тут примерный пример того, как работает поддержка корутин у ретрофита начиная с версии 2.6.0. Все очень просто и нужно всего лишь заюзать модификатор suspend)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            val arguments = Bundle().apply {
вместо Bundle().apply {...} можно использовать 
```
bundleOf(
  "key1" to value1
  "key2" to value2
)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            .setMessage("R.string.permission_rationale_location")
По-моему здесь должен быть ресурс, а не строка)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            Toast.makeText(activity, "permission_required_toast", Toast.LENGTH_SHORT).show()
Текст довольно странный. Давай занесем строку в ресурсы и все-таки зададим значение на русском?

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            requireContext().launchActivity<MapActivity>()
Лучше вызывать requireActivity().launchActivity. 
Если запускать активити через контекст (application) - она стартует в новом таске.

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    val pickupsLiveData: LiveData<PickupsUiResponse> = mPickupsLiveData
Кстати, по поводу заведения двух полей на viewModel: в android architecture недавно появилась довольно крутая билдер-функция liveData {...} которая позволяет запустить корутину в ней и класть в нее значения. Идеально подходит как раз для случая с запросом) 
https://developer.android.com/topic/libraries/architecture/coroutines#livedata можешь тут почитать. Возможно, поможет чуть улучшить читаемость кода 

У тебя получится прямо-таки очень наглядный флоу работы:
```
val pickupsLiveData: LiveData<PickupsUi> = liveData { 
  emit(Loading)
  try { 
    val result = repo.getPickups()
    emit(result)
  } catch (e: Exception) { 
    emit(Error)
  }
}
```
Я, конечно, утрировал, но что-то похожее должно выйти) 
}

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +    activity: AppCompatActivity, requestId: Int,
каждый новый параметр переносим на новую строку, иначе это плохо читается.

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +    grantPermissions: Array<String>, grantResults: IntArray, permission: String
переносим каждый параметр на новую строку

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            val fromLocation = Geocoder(this, Locale.getDefault()).getFromLocation(
В идеале, кстати, завернуть получение локации из геокодера в свой репозиторий, вроде GeoInfoRepository, в который бы провайдился контекст.
В идеале можно передавать в него локацию, а получать на выходе строку с адресом. И бандл с информацией о том, что показать в маркере, формировать на стороне ViewModel. 
Флоу работы будет таким: 
* кликаем по маркеру 
* говорим viewModel о том, что был осуществлен клик
* viewModel идет в геокодер и достает адрес
* viewModel вычисляет дистанцию между маркером и текущим положением
* оборачиваем все данные для показа маркера в класс вроде PickupInfoUi
* эмитим во viewModel значение в liveData из этого класса.
* на вью отображаем pickup_root_layout и данные из этого класса.

Таким образом, мы сохраним в целости ответственность вью, и не будем сильно раздувать ее логику. Она должна быть максимально пассивной.

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            activity_map_pickup_distance_text.text = viewModel.getDistance(lastKnownLocation, marker.position)
Мы не можем просто взять и достать данные из viewModel, это ломает архитектуру и unidirectional data flow. 

Вью может только подписаться на liveData. Я отписал про это в комменте выше

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +        pickupsResponse.forEach { pickups.add(it.convert()) }
Нам в принципе не нужно здесь создавать новый список и добавлять в него элементы.
гораздо проще будет использовать map-функцию: pickupsResponse.map { it.convert() } - она смаппит все как тебе нужно, и без промежуточных действий)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +            String.format("%.3fм", sqrt((x2 - x1).pow(2.0) + (y2 - y1).pow(2.0)) * 1000)
Форматированием лучше заняться вьюхе. Возвращай отсюда int-значение в метрах)

2020-07-01 15:12 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    fun getDistance(firstLocation: Location?, secondLocation: LatLng): String {
Зачем нам здесь получать nullable-поле?
Может быть, лучше просто сразу до вызова метода проставить distance=-1, если firstLocation == null? 
И даже не вызывать этот код.
Ну и вполне можно в таком случае на вью сделать проверку вроде if(distance=-1), то скрываем textView с локацией

2020-07-02 07:43 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/models/domain/LatLng.kt
> +data class LatLng(
Окей!

2020-07-02 08:23 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/repository/MapActivityRepository.kt
> +    fun getPickups(
Готово

2020-07-02 08:31 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            val arguments = Bundle().apply {
Понял!

2020-07-02 08:33 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            .setMessage("R.string.permission_rationale_location")
Точно xD

2020-07-02 08:39 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/dialog/RationaleDialogFragment.kt
> +            Toast.makeText(activity, "permission_required_toast", Toast.LENGTH_SHORT).show()
ОКей)

2020-07-02 08:41 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/AccountFragment.kt
> +            requireContext().launchActivity<MapActivity>()
Буду знать

2020-07-02 09:09 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    val pickupsLiveData: LiveData<PickupsUiResponse> = mPickupsLiveData
Переделал!

2020-07-02 09:10 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +        pickupsResponse.forEach { pickups.add(it.convert()) }
Точно!

2020-07-02 09:12 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +    activity: AppCompatActivity, requestId: Int,
Хорошо

2020-07-02 09:13 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/utils/Extensions.kt
> +    grantPermissions: Array<String>, grantResults: IntArray, permission: String
Хорошо

2020-07-02 11:38 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            val fromLocation = Geocoder(this, Locale.getDefault()).getFromLocation(
Хорошо

2020-07-02 11:56 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +            activity_map_pickup_distance_text.text = viewModel.getDistance(lastKnownLocation, marker.position)
Сделал

2020-07-02 11:56 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +            String.format("%.3fм", sqrt((x2 - x1).pow(2.0) + (y2 - y1).pow(2.0)) * 1000)
Окей!

2020-07-02 11:56 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/viewmodel/MapActivityViewModel.kt
> +    fun getDistance(firstLocation: Location?, secondLocation: LatLng): String {
Хорошо

2020-07-08 07:04 UTC, midery approved these changes

2020-07-08 07:04 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +    private fun onMyLocationClick(location: Location) {}
Нужен ли этот метод и лиснер, если в нем ничего не происходит?)

2020-07-10 04:09 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/map/MapActivity.kt
> +    private fun onMyLocationClick(location: Location) {}
Если его убрать, то кнопка для перехода к текущему местоположению не работает  :(

2020-07-10 04:10 UTC, merged