Work on b7-t01. Handler. Анти-пример
Golgoroth22/rebrain-android pull request #49
Opened 2020-07-10 05:52 UTC by Golgoroth22

2020-07-11 10:41 UTC, midery requested changes

2020-07-11 10:41 UTC, midery commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private fun changeTitle() = Handler().postDelayed({
Ты неверно понял задание) 
Нужно было создать новый поток, и в нем запустить код с задержкой 1000мс, а ты послал код в текущий поток с задержкой 1000мс. Поэтому ничего не крашнулось и все ок) 

Советую почитать про модель процессов и потоков в java по этой ссылке: https://habr.com/ru/post/164487/
И про потоковую модель android вот здесь: https://developer.android.com/guide/components/processes-and-threads?hl=ru

P.S.: когда научишься создавать потоки в стиле Java, и поймешь, как они работают, можешь попробовать синтаксический сахар от котлина: функцию thread { ... }. 
Очень удобная штука)

2020-07-12 14:06 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +    private fun changeTitle() = Handler().postDelayed({
Понял, спасибо!

2020-07-12 14:21 UTC, midery approved these changes

2020-07-13 08:15 UTC, merged