Work on task b3-t06. Work with affinitys
Golgoroth22/rebrain-android pull request #8
Opened 2019-03-26 17:06 UTC by Golgoroth22

2019-03-27 18:57 UTC, r3tam requested changes
Все почти отлично, маленькое замечание

2019-03-27 18:57 UTC, artem-zaitsev commented on app/src/main/res/values/strings.xml
> +    <string name="start_tusk">start.tusk</string>
лучще разграничьте по блокам(например с помощью комментариев) строковые константы. Иначе будут сливаться в одну неподдерживаемую массу

2019-03-28 16:28 UTC, Golgoroth22 commented on app/src/main/res/values/strings.xml
> +    <string name="start_tusk">start.tusk</string>
Исправлено!

2019-03-29 10:35 UTC, r3tam approved these changes

2019-03-29 15:09 UTC, merged