B3 t07. Work with ViewPager
Golgoroth22/rebrain-android pull request #9
Opened 2019-03-31 16:29 UTC by Golgoroth22

2019-04-01 06:42 UTC, r3tam requested changes

2019-04-01 06:42 UTC, artem-zaitsev commented on app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
в config.gradle

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +//    private lateinit var pageAdapter : CarouselPageAdapter
коментарии либо убирайте, лимбо поясняйте. Иначе другой разработчик будет долго думать, а необходим ли код.

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +//    private lateinit var pageAdapter : CarouselPageAdapter
Тем более, что можно просто объявить свойство типа PagerAdapter(как мне помнится обе реализации FragmentPagerAdapter его наследники).

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +private const val ARG_PARAM = "param"
Лучше давать название параметрам более смысловое.

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +            val bundle = Bundle()
есть полезный extension bundleOf() из [android ktx](https://developer.android.com/kotlin/ktx)

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselPageAdapter.kt
> +    fun addPicturesList(list: List<Int>) {
Думаю стоит подумать над передачей списка через конструктор. Так будет приятнее и логичнее.

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselStatePageAdapter.kt
> +    fun addPicturesList(list: List<Int>) {
то же , что и выше про список и конструктор

2019-04-01 06:42 UTC, artem-zaitsev commented on app/src/main/res/layout/activity_main.xml
> +    <android.support.v4.view.ViewPager
лучше сразу переехать на androidX

2019-04-01 06:42 UTC, artem-zaitsev commented on build.gradle
> +        support_v4 = versions.support_v4
переезжайте на AndroidX

2019-04-01 06:42 UTC, artem-zaitsev commented on config.gradle
> +versions.support_v4 = "28.0.0"
AndroidX

2019-04-01 14:58 UTC, Golgoroth22 commented on app/build.gradle
> +    implementation 'com.android.support:design:28.0.0'
Поправил!

2019-04-01 14:58 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +//    private lateinit var pageAdapter : CarouselPageAdapter
Поправил!

2019-04-01 14:59 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +private const val ARG_PARAM = "param"
Поправил!

2019-04-01 14:59 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselPageAdapter.kt
> +    fun addPicturesList(list: List<Int>) {
Поправил!

2019-04-01 16:00 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +            val bundle = Bundle()
Поправил!

2019-04-01 16:00 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselStatePageAdapter.kt
> +    fun addPicturesList(list: List<Int>) {
Поправил!

2019-04-01 16:00 UTC, Golgoroth22 commented on app/src/main/res/layout/activity_main.xml
> +    <android.support.v4.view.ViewPager
Поправил!

2019-04-01 16:01 UTC, Golgoroth22 commented on build.gradle
> +        support_v4 = versions.support_v4
Поправил!

2019-04-01 16:01 UTC, Golgoroth22 commented on config.gradle
> +versions.support_v4 = "28.0.0"
Поправил!

2019-04-02 06:39 UTC, r3tam requested changes

2019-04-02 06:39 UTC, artem-zaitsev commented on app/build.gradle
> +    implementation "com.google.android.material:material:$support_v4"
не стоит оставлять саппорт даже в названии версии

2019-04-02 06:39 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        viewPager = findViewById(R.id.main_view_pager)
можно обращаться сразу через kotlin.synthetic - по идентификатору в xml

2019-04-02 06:39 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +
лишняя пустая строка

2019-04-02 06:39 UTC, artem-zaitsev commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselStatePageAdapter.kt
> +    override fun getItem(p0: Int): Fragment {
лучше использовать более осмысленные названия в аргументах(даже если студия генерирует не совсем хорошие)

2019-04-02 15:19 UTC, Golgoroth22 commented on app/build.gradle
> +    implementation "com.google.android.material:material:$support_v4"
Поправил!

2019-04-02 15:33 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/MainActivity.kt
> +        viewPager = findViewById(R.id.main_view_pager)
Поправил!

2019-04-02 15:34 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/CarouselFragment.kt
> +
Поправил!

2019-04-02 15:41 UTC, Golgoroth22 commented on app/src/main/java/com/falin/valentin/foodapp/screen/main/carousel/adapter/CarouselStatePageAdapter.kt
> +    override fun getItem(p0: Int): Fragment {
ПОправил!

2019-04-03 14:50 UTC, r3tam requested changes
все хорошо, заметил только одну вещь - вы запускаете главный экран через контекст приложения(IntroActivity, слушатель кнопки). Лучше использовать контекст активити в этом случае.
Поправьте

2019-04-03 15:40 UTC, Golgoroth22 commented
> все хорошо, заметил только одну вещь - вы запускаете главный экран через контекст приложения(IntroActivity, слушатель кнопки). Лучше использовать контекст активити в этом случае.
> Поправьте
Поправил!

2019-04-04 16:49 UTC, r3tam approved these changes

2019-04-05 10:35 UTC, merged